QB64-Phoenix-Edition/QB64pe

SAMPLES.txt
licenses/COPYING.TXT
qb64.1

Remove more references from old .org site to our new site.

Update more links

---

source/ide/wiki/wiki_global.bas
source/ide/wiki/wiki_methods.bas

Some final fixes before the next release.

Fixes to blank line checks.

---

source/global/version.bas

Updates the version for the next release, v0.8.0

Update version to 0.8.0

---

source/global/version.bas

We've addressed a few bugs found on the forums, I'm looking to put out a small patch release with those fixes in it.

Update version to v0.8.1

---

source/global/version.bas

Update version number to 3.1.0

Version v3.1.0

---

source/global/version.bas

Bump the version number to 3.2.0, with a release intended later today.

Version 3.2.0

---

source/global/version.bas

I believe the relevant changes are #180, #182, and #184, so only bug fixes this time :)
Additionally on the Wiki side @RhoSigma-QB64 has finished/fixed the list of _GL commands in the Wiki, which will then also be present as updated help files in the IDE.

Version 3.2.1

---

source/global/version.bas

The minor bump is due to #204 and #208. There's a handful of bug fixes in there as well.

Version 3.3.0

---

source/global/version.bas

This is a major version update due to the addition of new commands in #216. There is the #222 fix in here as well.

Version 3.4.0

---

source/utilities/s-buffer/readme.txt
source/utilities/s-buffer/simplebuffer.bm

Implements the latest refactoring changes done in my Simplebuffers library.

Simplebuffers refactoring

---

internal/c/parts/gui/tinyfiledialogs.c

tinyfiledialogs had lots of issue surrounding the quoting of the arguments to the dialog functions. The arguments are effectively placed verbatim into shell commands, and without any proper treatment they would get accidentally evaluated by the shell, which is a big problem. Additionally, any arguments containing quotes would just not work since they would screw up the underlying shell command.
This change fixes all that for Linux. Every argument to the dialog functions is now surrounded in single quotes, which prevents any evaluation of the string by the shell. Additionally, because this is standard the only characters that need special treatment are the single quote characters, and proper escaping for them has been added. The result is that the dialog functions can now accept arguments …

Fix quoting of arguments to dialog functions on Linux

---

internal/c/parts/gui/tinyfiledialogs.c

Fairly straight forward, the Powershell code was fundimentally just calling Shell_NotifyIcon under the covers which we can easily do ourself. The notification has to be tied to a window, so I simply create a hidden one to use.
A nice improvement here is that instead of having to use the Powershell icon we can make use of the EXE icon if one was provided. If one is not provided then we use the default 'application' icon. Additionally quotes can be in the message and title now with no issues.
Ex:

Swap NotifyPopup to use Shell_NotifyIcon

---

source/global/IDEsettings.bas
source/ide/ide_global.bas
source/ide/ide_methods.bas
source/qb64pe.bas

And without screwing up the keyword casing this time!  ;)

Swap in Optional New Load File Dialog

---

internal/c/qbx.cpp
source/qb64pe.bas

Just filling some spare time :), closing #119

Simplify #include

---

source/global/version.bas

We've had a bunch of changes going into here, but the HTTP(s) stuff at a minimum justifies a minor version bump since it's a new feature. @a740g's audio changes also include new features.

Version 3.5.0

---

source/subs_functions/subs_functions.bas

This is for an issue that @mkilgore caught. See https://github.com/QB64-Phoenix-Edition/QB64pe/pull/279#discussion_r1097240194

Tiny PR that corrects the arg. count for _SNDNEW and type for _COLORCHOOSERDIALOG

---

source/global/version.bas

This is a minor release due to #286 which adds a new feature to open images from memory.

Version 3.6.0

---

internal/c/parts/audio/miniaudio.h

Related to #320 
David bumped up the version number to v0.11.13 😁

miniaudio version number bump

---

source/ide/ide_methods.bas

- strip useless line feeds after last code line
- fix some wrong wiki links

Export finetuning

---

source/global/version.bas

There's some new sound file formats supported (also likely the new font stuff as well) so it's a minor release.

Version 3.7.0

---

source/ide/ide_methods.bas

Added the ability to use the Save Dialogs in the IDE.

Savefile GUI added to IDE

---

internal/c/parts/core/src/freeglut_window.c

When QB64-PE is compiled with LLVM-MingW, it offsets the Windows client RECT in such a way that part of it is hidden underneath the title bar. See image below. Also see https://qb64phoenix.com/forum/showthread.php?tid=1714
I tracked this down to the `fghComputeWindowRectFromClientArea_UseStyle()` function. Then, after comparing this to the [latest version](https://github.com/FreeGLUTProject/freeglut/blob/e9ceb6dd8df0b4b289b547e141ddb70b7f36cfe2/src/mswin/fg_window_mswin.c#L413) of FreeGLUT, I saw that the new implementation was much simpler. So, I replaced the old implmentation with the new one.
We should seriously consider moving to the latest version of FreeGLUT. I suspect that #349 is also related to the version of FreeGLUT that we are using.
This PR help us to move a little closer to …

Fix incorrect client RECT offset when compiled with LLVM-MingW

---

source/ide/ide_methods.bas

This PR fixes the following:
- Save dialog now shows *.bas files
- Default_StartDir is now shared between OpenFile() and SaveFile()

IDE Open & Save GUI dialog fixes

---

source/ide/ide_methods.bas

see https://qb64phoenix.com/forum/showthread.php?tid=2017&pid=19971#pid19971

Feature request

---

source/global/version.bas

This adds _SAVEIMAGE, adds initial Windows on ARM support, removes the OpenAL audio backend, fixes few issues with PRINT and fonts, adds QOA and QOI format support, adds pixel scaler support, adds `Save As` GUI dialog to the IDE and some IDE and compiler fixes.

Version 3.9.0

---

source/global/version.bas

This release updates the version to 3.9.1 and includes fixes for the math bug and the menu issue that made its way into 3.9.0.
See #387 & #385 for more details.

Version 3.9.1

---

docs/build-system.md
source/global/version.bas
source/qb64pe.bas

- added embed info to docs
- finalizing the new release

Bump Version

---

source/qb64pe.bas

Yet again, here's another patch to the patch which patches a patch....  /sigh
This should fix the &H, &b, and &O issues by taking the values directly for us, and the math evaluator no long does those for us.
This should also fix a glitch with suffixes eatting part of the expression they should be evaluating and not returning the correct value.

fix for CONST issues

---

source/global/version.bas

This release updates the version to 3.11.0.
The following PRs are part of this version: #422, #421, #420, #419

Version 3.11.0

---

internal/c/libqb/src/filesystem.cpp

This PR includes two important fixes:
1. The `FS_IsPatternMatching()` function has been updated to perform case-insensitive matches on Windows.
2. `_FILES$` will now default to the `*.*` pattern if called with an empty string for the first time. Additionally, it will no longer throw an error if the `fileSpec` is not found.
Both changes align with the behavior of the `DIR$` function in BASIC PDS 7.1.
The issue was reported here: https://qb64phoenix.com/forum/showthread.php?tid=2376&pid=22787#pid22787.
Moreover, the second point was also discussed on Discord, but the changes were unintentionally omitted by me in #426. 🙁

Fix case-insensitive pattern matching on Windows and _FILES behavior

---

source/qb64pe.bas

As discussed in the Discord channel.

Fix $IF prioritization

---

source/qb64pe.bas

Fixes #461

---

source/ide/ide_methods.bas

Simple change in the IDE error reporting to change all instances of "Caused by SUB VWATCH" to make it "Caused by End of Program", which makes more sense to me, overall.

Change to IDE reporting

---

source/global/version.bas

This version includes the changes in #491.

Bump version to 3.13.1

---

source/ide/ide_methods.bas

Export fixes

---

internal/c/common.h
internal/c/libqb.cpp
internal/c/libqb/include/extended_math.h
internal/c/libqb/include/game_controller.h
internal/c/libqb/include/mac-mouse-support.h
internal/c/libqb/include/qbs.h
internal/c/libqb/src/datetime.cpp
internal/c/libqb/src/filepath.cpp
internal/c/libqb/src/glut-main-thread.cpp
internal/c/libqb/src/http-stub.cpp
internal/c/libqb/src/qbs.cpp
internal/c/libqb/src/qbs_cmem.cpp
internal/c/libqb/src/qbs_mk_cv.cpp
internal/c/libqb/src/shell.cpp
internal/c/parts/gui/tinyfiledialogs.c
internal/c/parts/input/game_controller/game_controller.cpp
internal/c/qbx.cpp
source/ide/ide_methods.bas

The PR silences many compiler warnings generated when compiling under Windows using MinGW gcc / clang.

Silence C++ compiler warnings

---

source/ide/ide_export.bas

- adapting code export for new SOUND variants WAIT and RESUME

Export adjustment

---

internal/c/parts/audio/audio.cpp
internal/c/parts/audio/extras/primesynth/primesynth.cpp

Changes:
- Moves the call to `BufferMap::ReleaseBuffer()` from `VFS::OnClose()` to `AudioEngine::ReleaseHandle()`. This fixes an issue where the buffer reference count would not be correctly decremented if the same sound file were opened, played, and closed multiple times in a loop.
- Silences multiple C++ compiler warnings.

Avoid calling BufferMap::ReleaseBuffer() from VFS::OnClose()

---

internal/c/parts/audio/audio.cpp
internal/c/parts/audio/extras/hively_ma_vtable.cpp
internal/c/parts/audio/extras/midi_ma_vtable.cpp
internal/c/parts/audio/extras/mod_ma_vtable.cpp
internal/c/parts/audio/extras/qoa_ma_vtable.cpp
internal/c/parts/audio/extras/radv2_ma_vtable.cpp

Nothing serious. I messed up the log levels in the last PR mostly using info logs instead of trace. This resulted in polluting the log output. This PR moves most logs to trace and warn levels using info sparingly.

Fix log levels
