source/qb64.bas
tests/compile_tests/versioninfo2/test.bas
tests/compile_tests/versioninfo3/test.bas

The Windows resource file we create contains two separate values for FileVersion and ProductVersion. Currently, they are actually represented by two separate values in $VERSIONINFO and effectively require duplicating the information between them.
My understanding is that the string values should always be the same as the numerical versions, so to make $VERSIONINFO easier to use this changes the logic so that setting the numerical version will automatically also set the string version if values for them are not provided.
Ex. This change makes it so this:
```
$VERSIONINFO:ProductVersion#=1,2,3,4
```
Is equivalent to this:
```
$VERSIONINFO:ProductVersion#=1,2,3,4
$VERSIONINFO:ProductVerison=1,2,3,4
```
The previous version is still allowed

Allow numerical $VERSIONINFO values to set corresponding string values

---

internal/c/libqb.cpp
tests/.gitignore
tests/qbasic_tests.sh

Currently there is a bug where if a variable width font is in use and
text printed would exactly fit to the end of the row, it is instead
wrapped and printed on the next line.
Ex. You're printing a character that is 10 pixels wide, starting
from position 90 on an image that is 100 pixels wide. This should fit,
but instead your character will be printed on the next line.
The reason this happens is an off by one error, cursor_x (effectively
the X value passed to LOCATE) is one based even when using a variable
width font where cursor_x represents a pixel location. The location that
check if the next character can fit on the screen never handles the base
one, so it ends up treating the ending Y coordinate as one past where it
will actually end, which makes the code thing the print will go …

Fix text wrapping on last column with variable width fonts

---

internal/source/icon.rc
internal/source/manifest.h
internal/source/qb64.manifest

This issue was fixed in 4d61ff79, but due to how ./internal/source is
updated the new ./internal/source files were compiled using a QB64
without the fix, producing files with the wrong quoting. Previously this
was worked around because the build process overwrote these files, but
the `Makefile` build requires them to be fixed.
./internal/source itself is fine, so it's easy enough to simply fix the
files by hand. Since ./internal/source now contains a compiled QB64 that
contains the fix from 4d61ff79 it's generated files will have proper
quoting and won't need to be manually updated.

Fix quoting in Windows-specific files in ./internal/source

---

Makefile
setup_win.bat

The `setup_win.bat` was not previously reporting an error if the compilation fails, so I changed it to indicate that something went wrong and report an exit code. This has the benefit that it will fail the build if there is something wrong with the `setup_win.bat` test.
Also, the `objcopy` is bugged on Windows and does not work on OSX, so I'm going to modify the logic to work on Windows and simply remove the functionality from OSX.

Add error handling to setup_win.bat, fix objcopy command

---

internal/c/libqb.cpp

Fixes the issue as brought up on the forums here: https://qb64phoenix.com/forum/showthread.php?tid=408
Also added a small set of logic so we don't end up inside an endless loop if the screen is hidden (via _SCREENHIDE), or if it doesn't exist for whatever reason.

Fix to _desktopwidth, _desktopheight, _screenicon

---

setup_win.bat
source/qb64.bas

Added to win setup to clean up the mingw compiler after installation.
Fixed the issue where some Linux distros won't clean up the exe when Run Only is selected in the menu bar.
Fixes: #16
Fixes: #54

Steve's changes in #73, with fixed history.

---

Makefile
source/global/version.bas
source/qb64.bas
tests/compile_tests.sh

The commits include more detail descriptions, but brief descriptions of the fixes
1. qbx.o always listed `./internal/temp/*.txt` as the dependencies, rather than using the proper `temp*` directory depending upon the ID being used. This meant `qbx.o` would not always get recompiled when it should.
2. The `.sym` files was not getting correctly generated because the directory was left in the name, producing an invalid path. The fix is to just strip the leading path off, which is what I intended when I put it in.
3. Compiling executables with spaces in their name or path would not work. This is an issue with Make, but I was able to work around it since the executable name is not a list and is the only thing that's a path we don't control. I added testing for this as well.
I also bumped the …

Fix various identified Makefile issues

---

tests/compile_tests/name with spaces/test.bas
tests/compile_tests/name with spaces/test.output

I meant to add this test in my previous PR but it got missed. It's not extremely important because I put a space in all of the test executable names, but this adds a test that includes a space in the directory name for the executable as well.

Add missing test for directory with spaces

---

.github/workflows/ci.yml

The OSX and Linux build artifacts have `x64` in the name even though they're both 32-bit and 64-bit compatible. It's causes some confusion.
Fixes: #78

Remove 32-bit/64-bit distinction from Linux and OSX artifact name

---

docs/build-system.md

Adds a fair amount of documentation on the build system. Includes information on the CI process, the `Makefile` parameters, versioning, and release process.
Fixes: #83

Add documentation of the build system

---

Makefile
docs/build-system.md
setup_lnx.sh
setup_osx.command
source/global/IDEsettings.bas
source/ide/ide_methods.bas
source/qb64.bas
source/utilities/strings.bas

The new dialogs includes 5 settings:
1. Flag to turn on Optimization (off by default)
2. Flag to strip symbols (On by default)
3. String for extra compiler flags
4. String for extra linker flags
5. Setting for max compiler processes (default of 3)
The "Advanced (C++)" dialog was removed, putting the single setting into
the new C++ Compiler Settings dialog.
Fixes: #65
Fixes: #40

Add ide compiler settings dialog

---

Makefile
source/qb64.bas

This is a bit of an odd one, but files with $ in the name don't compile
correctly due to expansion being done on the $.
The culprit here is `make`, as the syntax '$x' is interpreted to mean to
insert the expansion of the variable 'x'. To avoid this behavior we have
to replace every single $ with `$$`. Make will interpret the `$$` to mean it
should insert a single $ and not do any expansion, which is what we
want.
Fixes: #96

Fix compilation of files with $ in the name

---

.ci/common-exclusion.list
.ci/lnx-exclusion.list
.ci/make-dist.sh
.ci/osx-exclusion.list
.ci/read-version.sh
.ci/win-exclusion.list
.github/workflows/ci.yml

The artifacts like `qb64-lnx.tar.gz` will now also include the version
in their name, making them `qb64-lnx-X.Y.Z.tar.gz` instead.
Fixes: #104

Add version to artifact name

---

source/ide/ide_methods.bas

The C++ compiler Settings menu uses the shortcut key 'o', but that's
actually already in use and thus creates a conflict. We're switching it
to use the option 'm', which does not conflict.
Fixes: #105

The C++ settings menu reuses existing shortcut key

---

source/global/version.bas
source/ide/ide_methods.bas

#107 broke the C++ Compiler Settings menu because I forgot to update the string where we check of menu was clicked :-/
This also bumps to v0.8.2, so we can make a release with this fix.
I made sure to test it with the correct compiled copy of QB64 this time 🤦 ...

Fix C++ compiler settings menu

---

.ci/compile.bat
.ci/compile.sh
.github/workflows/ci.yml
Makefile
internal/c/libqb.cpp
internal/c/libqb/build.mk
internal/c/libqb/include/buffer.h
internal/c/libqb/include/completion.h
internal/c/libqb/include/condvar.h
internal/c/libqb/include/libqb-common.h
internal/c/libqb/include/mutex.h
internal/c/libqb/include/thread.h
internal/c/libqb/src/buffer.cpp
internal/c/libqb/src/threading-posix.cpp
internal/c/libqb/src/threading-windows.cpp
internal/c/libqb/src/threading.cpp
internal/c/os.h
internal/c/parts/audio/out/src/config.h
tests/build.mk
tests/c/buffer.cpp
tests/c/test.cpp
tests/c/test.h
tests/run_c_tests.sh

This is a reasonably big one but I didn't see a better way to split it up, this is the next step after #102. If you have any questions please ask :)
The `./internal/c/libqb/` folder now has two new folders `./internal/c/libqb/src/` and `./internal/c/libqb/include` for headers and C++ source files contributing to libqb. These source files are all compiled independently into `.o` files, and then linked into the final application. Which of these files gets built and linked is determined by the logic in `./internal/c/libqb/build.mk`.
The `threading-*.cpp` files show the general approach for platform-specific implementations.  Depending on exactly how different the implementations for Windows/POSIX/x64/x86/etc... are we can avoid all the `#ifdef` logic everywhere by simply providing completely …

Add separate libqb folder with new APIs, along with C++ automated testing.

---

source/ide/wiki/wiki_methods.bas

Rather than declining page local links completely, simply link to the top of the respective page, except if it's on the currently displayed page.

Semi-support local links

---

source/qb64.bas

The math evaluator already contains a few checks for zero when we're
executing operations that could cause a `Divide By Zero` error, but the
actual value input is floating point and can get rounded to zero when
the operation happens. This effectively allows zero values to bypass the
checks to prevent them from being evaluated.
To avoid the error completely we need to check that the rounded value is
not zero, rather than the initial value. FIX() is used to make sure
values such a `-.1` round to zero and are avoided. I also applied FIX()
when we actually execute the operation, just to ensure the same
behavior.
---
This issue was originally reported for qb64official/qb64#4, and we experience the
same issue. Also, oddly, like stated in the title it does not actually trigger
a `Divide By Zero` …

Math evaluator: values that round to zero can crash QB64pe

---

source/qb64pe.bas
source/utilities/s-buffer/readme.txt
source/utilities/s-buffer/sb_qb64pe_extension.bi
source/utilities/s-buffer/sb_qb64pe_extension.bm
source/utilities/s-buffer/simplebuffer.bi
source/utilities/s-buffer/simplebuffer.bm

- No longer constantly (over)writes files in the `internal\temp` folder while typing in the IDE, as the generated C/C++ code is buffered internally now.
- Buffers are automatically written out to disk on a `Make` request (F5/F11).

Avoid excessive disk access while typing

---

Makefile

The -no-pie flag tells the compiler not to make a Position Independent
Executable. We don't really care which it chooses to make, but some file
explorers consider PIE executables to be shared objects and won't allow
you to run them directly. To avoid this, we're compiling with -no-pie.
Fixes: #142

Use -no-pie on Linux

---

internal/c/libqb/include/libqb-common.h

We started defining `_WIN32_WINNT` a little while ago to express that we
require Windows Vista or above for support. This enables us to access
some Windows Vista-only APIs. The fact that `WINVER` also needs to be
defined was missed, and it seems that defining one means the other no
longer gets defined automatically as it did before. Thus we're simplying
now also defining `WINVER` the same as `_WIN32_WINNT`.
This fixes High-DPI awareness and a few other things that were gated
behind WINVER checks.

Fix High-DPI awareness on Windows

---

.github/workflows/build-process.yml
.github/workflows/pr.yml
.github/workflows/release.yml

Splitting up the build process into separate workflows makes it easier
to differentiate the builds for each, since each Workflow will get a
different name and history of builds. The actual build process remains
the same.
A screenshot of the result is below:
`CI` only contains builds of `main`. `PR` contains every `PR` build. `Release` contains tagged release builds. `QB64-PE Build Process` doesn't get any builds under it, but I couldn't see an obvious way to not make it get listed. The big win here is that the build history for each of these is separate.
Edit: Note that I tested all of the workflows individually in my fork to verify this works :)

Split up workflows

---

internal/c/libqb.cpp

DPI Awareness allows a program to tell Windows that it will handle
properly scaling itself for the screen's DPI. Thus when a program is DPI
Aware, it will always see the actual screen size. When a program is not
DPI Aware, then Windows will scale the program according to the
selection by the user, and the reported screen size will match the
scaled size rather than the actual screen size.
Commit 189cdb8e added logic to enable DPI Awareness on Windows, but it
was hidden behind a `WINVER` check. This meant it was not actually in
use because at the time QB64 did not set a `WINVER` high enough to
actually enable that code. As such all Windows versions of QB64
including v2.0.2 were not DPI Aware.
Much later-on, Commit 869e361e declared a `_WIN32_WINNT` of `0x0600`,
which seems to have also …

Remove DPI Awareness on Windows

---

internal/c/common.h
internal/c/parts/audio/audio.cpp

This corrects an issue with `_MEMSOUND`, where it was using the older .TYPE values (prior to 1.000) instead of values for version 1.000 and up. This also lets users easily detect more sample formats when using `_MEMSOUND` in their code.

Fix usage of `mem_block` `type` in `_MEMSOUND`

---

Makefile
source/qb64pe.bas
tests/compile_tests/single'quote'test/single'quote'test.bas
tests/compile_tests/single'quote'test/single'quote'test.output

Using single quotes in a file name wasn't working because the Makefile
was using single quotes itself to quote the filename when providing it
to the compiler. The Makefile was switched to use double quotes instead,
which work just as well but are allowed to contain single quotes inside
of them.
Since double quotes are a legal character to have in a file name on
Linux and Mac OS, I added extra logic to start escaping double quote
characters.
I added a test to verify that we can compile source files with single
quotes in the name. I could not add a test for double quotes since such
files cannot exist on Windows and thus cannot easily be added to the
repository.

Fix compiling source files with single quotes in name

---

internal/c/libqb.cpp

`sub__mousemove` is trying to use `x_scale`, `y_scale`, `x_offset`, and
`y_offset` to calculate where the mouse should be in the event the
window coordinates are different from the screen coordinates.
Unfortunately, all four of those variables are actually never set in the
program. The real scale values and offsets (in the event of
letterboxing) are stored in `environment_2d__` values. This change
switches `sub__mousemove` to simply use the correct values when
calculating the mouse position.
Because `x_scale` and `y_scale` are not used anywhere else I just
removed them completely. I wanted to remove `x_offset` and `y_offset` as
well but there are a few spots that make use of it. It must be a bug,
since they are never assigned values other than zero, but I'm not sure
if the correct fix for …

Fix _MOUSEMOVE when window is resized

---

setup_win.bat

Since errorlevel wasn't enclosed in percents, it wasn't catching the 64 bit choice. Added percents around it and now it is allowing a 64 bit choice.

Fix errorlevel check

---

source/qb64pe.bas
tests/compile_tests.sh
tests/compile_tests/extra/include_extra.bi
tests/compile_tests/extra/include_extra_include.bi
tests/compile_tests/extra/include_extra_target.bi
tests/compile_tests/include_paths/include_fixed_compile_location.bas
tests/compile_tests/include_paths/include_fixed_compile_location.output
tests/compile_tests/include_paths/include_multiple.bas
tests/compile_tests/include_paths/include_multiple.output
tests/compile_tests/include_paths/include_relative.bas
tests/compile_tests/include_paths/include_relative.output

Fix was pulled from QB64Official/qb64#17 by @DualBrain, I just added tests around it.
Most (all?) compilers allow you to run the compiler from a separate directory than the compiler itself is located in and compile source files relative to that directory. QB64-PE however does not allow that, for a variety of reasons it always search for the provided source file relative to the location of the QB64-PE compiler rather than the CWD it was run from. This is pretty unexpected behavior in a lot of cases, and also doesn't give very helpful error messages either.
This change has us check if the source file exists at the given CWD location, and if it does we will prepend the CWD to produce the correct path to the file.
To test that this behavior works as expected I modified `compile_test.sh` to …

Fix compiling bas files relative to the CWD

---

qb64pe.1

Fairly simple, the man page was missing some of the switches (the new one I added, and also some older ones). The `-v` also had the wrong documentation.
Fixes: #199

Add and fix options listed in manpage

---

internal/c/libqb/include/audio.h
internal/c/parts/audio/audio.cpp
internal/c/parts/audio/out/src.c
internal/c/qbx.cpp
source/subs_functions/subs_functions.bas

This implements enhancements to `_SNDPLAYCOPY` as described in #185.
The extra `[, x!][, y!][, z!]` parameters are optional and hence this does not have any breaking changes.
The extra parameters can also be used with the old OpenAL audio backend. However, it does not change the properties of the sound.
We could have backported this feature to the OpenAL backend. However, considering that it is on life-support and may be removed it the future, I do not see any incentive.
This also corrects a minor typo in the help text for `_SNDBAL` that I discovered while implementing the changes in `subs_functions.bas`.

Implement `_SNDPLAYCOPY` enhancement #185

---

setup_osx.command
tests/dist_tests.sh

I broke this by accident in 5031de2, likely by misreading the $0.  What the line was intended to do was change to the directory the script is located in when the script starts, this allows the script to be started from any location.
Typically this isn't necessary functionality, but for Mac OS it's important because if you double-click the script (the typical way to run it) it is started from the user's home directory. Due to this I also updated the Mac OS distribution test to run the script in this way so that it's closer to how a user will run it.
Fixes: #218

Fix setup_osx.command script when run from a different directory

---

internal/c/parts/gui/tinyfiledialogs.c
internal/c/parts/gui/tinyfiledialogs.h

This fixes the `tinyfiledialogs` `yesnocancel` messagebox bug that @SpriggsySpriggs caught while testing. The issue was found to be in tinyfd_messageBoxW() that was not handling the `yesnocancel` (`MB_YESNOCANCEL`) case. I reported the issue to the tinyfiledialogs author `Vareille` who then acknowledged and pushed a fix for the issue [here](https://sourceforge.net/p/tinyfiledialogs/code/ci/4927ea8f44fa0151dc8e0a2b79a13dbd7827cc48/).

Update `tinyfiledialogs` to v3.8.9

---

internal/c/parts/gui/gui.cpp

If `aAllowMultipleSelects` is < 0 `tinyfd_openFileDialog()` allows a program to force-free any working memory that it may be using and return NULL. This is really not an issue even if it is not done because `tinyfd_openFileDialog` 'recycles' it working memory on each call and anything not feed will be taken care of by the OS on program exit. Unfortunately, in case of QB64, true is `-1` and passing this directly to `tinyfd_openFileDialog()` causes the function to show nothing. To work around this, we check for any non-zero value and re-interpret those as 1.

Fix _OPENFILEDIALOG$ to accept -1 for allowMultipleSelects&

---

internal/c/parts/gui/tinyfiledialogs.c

Escaping the osascript commands requires two layers of escaping: One for the script itself, and one for the sh arguments.
For the script itself, we simply have to escape the `"` character with `\"`. We then take the result of that and escape it suitably for sh arguments in single quotes. We already have a function for that so we simply call that to do the job.

Fix osascript escaping on Mac OS

---

internal/c/parts/gui/tinyfiledialogs.c

This removes the VBS based InputBox for Windows and replaces it with a
version that uses DialogBoxIndirect to create the dialog. While it is a
bit more complicated in some respects, it removes any concerns about the
contents of the strings as they're no longer being inserted into the
generated script. It also has the advantage that it doesn't spawn
another process (which then shows up in the task bar in some situations).
With this changes quote characters are allowed in all of the parameters.
Additionally this is the last set of changes for Windows, Mac OS is the only
platform left.
This additionally contains the change caught by @a740g to mark the `lBuff`
array `static` in `tinyfd_openFileDialog()`. I also went ahead and removed
the last of the quote checks (which weren't doing anything …

Fix _InputBox$ on Windows to use DialogBoxIndirect, and a few other changes

---

internal/c/parts/gui/tinyfiledialogs.c

We were incorrectly treating the empty string and NULL the same and using a password dialog for both. It now has the correct behavior of displaying the password when provided the empty string, but just displaying a blank input box when provided NULL.
Note that QB64-PE internally flips the logic provided to `tinyfd_inputBox` - so `_InputBox$("title", "message")` provides the empty string as the default text, `_Inputbox$("title", "message", "")` provides `NULL` as the default text.

Fix password handling in _InputBox$ on Windows

---

source/global/version.bas

Bumping to version 3.4.1. This includes the PAINT fixes in #241, several fixes to the dialog functions, a bump of the MinGW version, and also the new `GUI Dialogs` option @SteveMcNeill added which uses the new dialog functionality for the IDE `Open` menu option. The last one is not exactly a bug fix, but I think it's close enough :shrug: To me it doesn't really seem to justify a `3.5.0`.

Version 3.4.1

---

source/ide/ide_methods.bas

Enhancement?  Bug Fix?  Whichever you want to call it.... :wink:
Basically this just fixes the file open dialog so that the first time it's called from QB64, it opens in the StartDir path.  Then, forevermore, it opens in the last folder that the user navigated to.  (Well, forevermore, until they close QB64 and open it back up once again fresh and new.)

Change to Open File Dialog

---

Makefile
source/qb64pe.bas

This PR combines three relatively small fixes for #255, #256, and #257:
1. The `Makefile` was missing the `DEP_HTTP` flag which is now required for QB64-PE's help to work.
2. Use of some commands like `$NoPrefix` no longer causes the "Beginning C++ output..." to get duplicated.
3. When using `-x` with a `_SourceDir$`-relative source file, if no `-o` flag is provided the executable is now placed into `_SourceDir$` (instead of being placed at the location of QB64-PE).
Fixes: #255
Fixes: #256
Fixes: #257

Fix QB64-PE dependency list, _StartDir$ relative compile with no -o, and command line output.

---

source/qb64pe.bas

This was overlooked in #258, previously this printing was being skipped over via a check of idemode, but after changing where it was located so it only prints once it now runs when using the IDE, which screwed up the drawing of the IDE screen.
The simple fix is to check for idemode before doing the printing, which is effectively what it was doing before.
Fixes: #266

Fix the 'Beginning C++' message to stop being printed when using the IDE

---

source/qb64pe.bas
source/utilities/build.bas

Currently nm (tool to extract symbol names from libraries) is run for every relevant Declare Library function. For large libraries from which many functions are used, this can significantly impact compile times.
This change only runs nm once per library, per compile. Output is stored in a per-library file in internal/temp, which is then read as needed. From my measuring in Windows (in a VM) with a large library, this reduces the time spent searching for each function from 34 seconds to 5.5 seconds.
The 5 seconds is spent reading in the nm output. It would be nice to only read this data in once per compile, but that would require a slightly more significant code change to keep it in memory.
I have tested this on Windows and Linux but not MacOS. Relevant compile_tests pass.

Reduce the number of times nm is invoked

---

setup_lnx.sh

I'm in the process of testing this on the various distros, but a fairly straight forward change. libcurl is now a required dependency and xmessage is not.
Fixes: #265

Add curl and remove xmessage from setup_lnx.sh

---

COPYING.txt
licenses/README.md

A tiny PR that:
- Changes `licenses/COPYING.TXT` to `licenses/README.md` in `COPYING.txt`
- Fixes a typo in `licenses/README.md`
- Adds HivelyTracker license to `licenses/README.md`

Fix license info

---

internal/c/libqb/src/http.cpp

Fairly simple, MacOS High Sierra's libcurl version is too old and not have `CURLINFO_CONTENT_LENGTH_DOWNLOAD_T`. This adds a version check to use the older version of that command which gives back a double instead.
Fixes: #287

Fix build on MacOS High Sierra

---

source/qb64pe.bas
source/utilities/elements.bas
tests/compile_tests/qb64pe/element.bas
tests/compile_tests/qb64pe/element.output
tests/compile_tests/qb64pe/hasFunctionElement.bas
tests/compile_tests/qb64pe/hasFunctionElement.output

Currently functions only have very limited optional argument support, this expands it so that we can have more complex sets of optional arguments for functions, such as multiple arguments where not all need to be provided. This will be used in the future for some upcoming functionality.
Note that this does not support any generic optional argument format, the commas always have to be provided unless an optional argument is at the end of the parameter list. Thus, if you have a format with one required and two optional arguments and you want to omit the first optional one, then you need to call it as `foo(2, , 3)`, rather than `foo(2, 3)`. This is important for avoiding ambiguous situations, and is how many SUBs currently handle this.
The two functions that violate that requirement are …

Add support for optional function arguments

---

source/qb64pe.bas
source/utilities/file.bas
tests/compile_tests/filename/filename.extra.extension.bas
tests/compile_tests/qb64pe/file.bas
tests/compile_tests/qb64pe/file.output

Current the -o flag will strip any "extension" on the provided filename, which is fairly problimatic on Linux and Mac OS since those executables do not have other extensions and names like "foobar.v1" will get the ".v1" stripped off. This can happen on Windows as well if you leave off the .exe (QB64-PE will add it for you, but also strip off the existing extension if there was one).
QB64-PE stripping off the ".exe" when provided that on Linux and Mac OS might actually be useful behavior people are relying on (so that they don't need to provide different names when compiling on Linux/Mac OS) so we are preserving that behavior and still removing the extension if it is exactly "EXE", otherwise we now leave it in place.
Fixes: #297

The -o flag should not strip extensions except for .exe

---

Makefile
internal/c/libqb.cpp
internal/c/parts/network/log.txt

There are three parts to this:
- `libqb.cpp`: All changes here are to satisfy errors that Clang threw while compiling. All of them involve casting and scope resolution.
- `log.txt` and `src.c` in `internal/c/parts/network/`: these two were dead / empty files that I removed while trying to upgrade `libcurl` to the latest version
- `Makefile`: Makefile was building the 32-bit ARM version of `libcurl` which then failed to link against 64-bit libraries and object files for the rest of the source. Initially, I thought this was due to an issue with `libcurl`'s makefile. Hence, I decided to update `libcurl` then. However, on close inspection, I found that `ARCH` was being set as `w32` [here](https://github.com/QB64-Phoenix-Edition/QB64pe/blob/2cb0db1e2885ec47d0f3edfa48c85efec4e55700/internal/c/pa …

Tiny fixes that allow the IDE to be compiled with LLVM MinGW

---

internal/c/parts/video/image/stb_image.h

Well, this is simple.
This PR updates `stb_image.h` to v2.28.
The following is the revision history:
`2.28  (2023-01-29) many error fixes, security errors, just tons of stuff`

Update stb_image.h to v2.28

---

source/ide/ide_global.bas
source/ide/ide_methods.bas
source/ide/wiki/wiki_methods.bas

Will add the "Export As..." item to the File menu and according functionality. This will probably need more work on special options, such as exporting whithout bg color or make keywords bold, maybe using a file save dialog etc., but it's now in a state where people can use/test it and we'll see what suggestions come in to improve on it.
The Wiki downloads got fixed to avoid the problems discussed in https://qb64phoenix.com/forum/showthread.php?tid=1521 in the future.

Code export and Wiki fixes

---

internal/c/parts/audio/extras/midi_ma_vtable.cpp
internal/c/parts/audio/extras/tinysoundfont/tsf.h
source/qb64pe.bas

This is a small PR and has two changes.
1. It updates `TinySoundFont` (`TSF`) to the latest version. The latest version of `TSF` adds SoundFont3 support (SF3 = SF2 + Ogg Vorbis compression). The SF3 support in `TSF` uses `stb_vorbis.c`. Since we are already using `stb_vorbis.c`, enabling SF3 support is trivial.
2. `$MIDISOUNDFONT` behavior was updated so that it now looks for SoundFonts relative to the source and `$INCLUDE` files in addition to what it was already doing.

Update TSF and add SF3 support and enhance $MIDISOUNDFONT behavior

---

internal/c/parts/audio/extras/radv2/opal.cpp
internal/c/parts/audio/extras/radv2/player20.cpp
internal/c/parts/audio/extras/radv2/validate20.cpp
internal/c/parts/audio/miniaudio.h

We already had RAD v2 format support. This PR adds RAD v1 support as well. It does so by using updated and bug fixed versions of `opal.cpp`, `player20.cpp` and `validate20.cpp`.
This also includes an update to miniaudio.

RAD v1 support

---

internal/c/parts/audio/audio.cpp

This fixes a potential segfault in `PLAY()` if it is used before `SOUND` or `PLAY`.
This also adds a tiny bit of silence after `BEEP` so that consecutive `BEEP`s sound unique and not like a long continuous sound.

Fixes a potential segfault in PLAY()

---

internal/c/libqb.cpp
tests/compile_tests/keyboard/devices_windows.bas
tests/compile_tests/keyboard/devices_windows.output
tests/compile_tests/keyboard/keyconsts.bi
tests/compile_tests/keyboard/sendinput.bi
tests/compile_tests/keyboard/sendinput.bm

Currently the Keyboard _Devices entry on Windows does not report all the key presses and releases. This is due to missing some messages in the form of WM_SYSKEYDOWN and WM_SYSKEYUP. Additionally Windows is weird about report the state of the individual shift keys, so we add some logic using GetAsyncKeyState() to fix that up.
Fixes: #333

Fix keyboard _Device on Windows

---

setup_mingw.cmd

This updates the MinGW toolchain to v12.2.0 r2.
This was released on Dec 11, 2022, and I've been using this since then for all my QB64-PE tests, PRs etc. I have not gotten any false positives with this and hope it will reduce the false positives we've been getting with r1.

Update MinGW toolchain to v12.2.0 r2

---

internal/c/libqb/include/image.h
internal/c/parts/video/font/font.cpp

This PR resolves the issue reported by @loopy750 here https://qb64phoenix.com/forum/showthread.php?tid=1756&pid=16896#pid16896
In addition to this, `_UPRINTSTRING` now works correctly when commands like `WINDOW` and `VIEW` are used.
Note: `_PRINTSTRING` partially works with `VIEW` where it only clips but does not offset the rendering relative to the viewport. This should be addressed in a separate PR. I'll add a card about it.

Fix fonts getting vertically misaligned

---

source/qb64pe.bas

This PR fixes `DECLARE DYNAMIC LIBRARY` to load shared libraries from the source path when `Output EXE to Source Path` is enabled.
Currently, when `Output EXE to Source Path` is checked and something like the following is used, it expects the shared library to be present next to the `qb64pe` executable.
```vb
DECLARE DYNAMIC LIBRARY "foo"
``` 
Prefixing a `./` to the library name does not help either because then it simply replaces the `./` with an absolute path.
To work around this, we simply do a few more checks to satisfy the `direct without path` condition and allow the user to place the shared library where their source file is located.

Fix DECLARE DYNAMIC LIBRARY path issue

---

Makefile

This PR changes the previous `-std=gnu++11` in the Makefile to `-std=gnu++14`.
As such, this change allows code the uses the relaxed rules for constexpr functions to compile correctly without generating the error: `body of 'constexpr' function not a return-statement`.

Bump minimum C++ version in Makefile to 14

---

source/utilities/file.bas

Fix to blank file before writing so larger files don't corrupt data when overwritten by smaller ones.

Patch to CopyFile

---

setup_mingw.cmd

This PR updates the MINGW toolchain to 13.1.0-rt_v11-rev1.
This was released back in May, and I've been evaluating it ever since. No issues found.

Update to GCC-13.1.0 with MinGW runtime v11

---

internal/c/libqb.cpp

This PR fixes an issue where when the following snippet is used in graphics mode, it will not honor `_KEEPBACKGROUND`.
```vb
_PRINTMODE _FILLBACKGROUND
PRINT "foo", "bar"
PRINT "foo"; STRING$(9, 1); "bar"
```
The change simply skips drawing the boxes using the background color when `_KEEPBACKGROUND` is set.
Issue was reported here: https://qb64phoenix.com/forum/showthread.php?tid=2020

Print spaces and tabs correctly when _KEEPBACKGROUND is set

---

internal/c/libqb.cpp
internal/c/parts/input/game_controller/src.c

This PR removes `using namespace std` from `libqb.cpp` reducing the possibility of identifier conflicts.

Remove usage of `using namespace std` from libqb

---

source/ide/ide_methods.bas

This fixes the error `MENU ITEM [Run #Only (No EXE) NOT IMPLEMENTED!` that occurs because the string below https://github.com/QB64-Phoenix-Edition/QB64pe/blob/82ecfc09c783f4647251b25e0dd0553415402632/source/ide/ide_methods.bas#L5931
does not match with
https://github.com/QB64-Phoenix-Edition/QB64pe/blob/82ecfc09c783f4647251b25e0dd0553415402632/source/ide/ide_methods.bas#L336
I changed the menu string in an earlier PR not knowing that we compare the string later to see if the menu was clicked.
We should seriously consider consolidating and moving these strings to `CONST`s or `DATA` to avoid these issues in the future.
This issue was reported here: https://qb64phoenix.com/forum/showthread.php?tid=2063&pid=20329#pid20329

Fix menu item `Run #Only (No EXE)`

---

internal/c/common.h
internal/c/libqb.cpp
internal/c/qbx.cpp

With the removal of `using namespace std;` we inadvertently started using some of the global math.h versions of these functions, which take different types and result in computation errors.
The fix is to prefix all these functions with std:: so that we go back to using the std:: versions.

Use correct math functions from std::

---

source/qb64pe.bas
source/subs_functions/subs_functions.bas

This PR adds the `std::` prefix to the C math function calls in `qb64pe.bas` and `subs_functions.bas`.
See #387 for more details.

Use correct math functions from std:: in qb64pe.bas and subs_functions.bas

---

Makefile
internal/c/parts/audio/miniaudio_impl.cpp

Due to Apple's stricter notarization process on `Ventura` & `Sonoma`, `miniaudio` is not able to link to relevant frameworks at runtime. This causes it to fallback to the `null-audio` backend and eventually not play any audio.
To workaround this issue, we bypass runtime linking on macOS.
See the macOS build section here: https://miniaud.io/docs/manual/index.html#Building
This issue was reported here: https://qb64phoenix.com/forum/showthread.php?tid=2016

Avoid miniaudio runtime linking on macOS

---

source/qb64pe.bas

Should fix both of these issues:
https://github.com/QB64-Phoenix-Edition/QB64pe/issues/193 
https://github.com/QB64-Phoenix-Edition/QB64pe/issues/224

Patch to CONST

---

source/ide/ide_methods.bas

String manipulation has too much overhead for larger files to write all at once.   The best write speeds, from multiple testing experiments in various conditions, come from simply using PUT to place the data line by line to the drive.
This change reflects that method of file saving.

Change IDE save method as discussed on Discord

---

Makefile
tests/compile_tests.sh

It seems to sometimes not be dead when we go to start it, presumably the `pulseaudio -k` doesn't actually wait for the process to exit.

Add a short delay after killing pulseaudio

---

internal/c/libqb/src/filesystem.cpp

The PR updates the behavior of `_FILES$` to match with the behavior detailed in the [wiki description](https://qb64phoenix.com/qb64wiki/index.php/FILES$) and as discussed on Discord.
I.e. if `filespec$` is omitted on the first call to `_FILES$`, it will generate the error message, "Illegal Function Call."

Make _FILES$() throw an error if it is called without an argument the first time

---

internal/c/libqb.cpp

This PR fixes an `OPEN COM` statement from locking up inside `gfs_open_com_syntax()`.
For example, the following code crashes with v3.9.0, v3.9.1 and locks up on later versions.
The issue was first reported here: https://qb64phoenix.com/forum/showthread.php?tid=2376&pid=22478#pid22478
```vb
ON ERROR GOTO Handler
OPEN "COM4:74880,N,8,1,BIN,CS0,DS0,RB8192" FOR RANDOM AS #99
END
Handler:
PRINT "Error:"; ERR
RESUME NEXT
```
With the changes in the PR, this no longer happens. The changes mostly consist of re-formatting the code and improving readability. But most importantly, it now returns `1` if it can completely parse the string.

Fix OPEN COM from locking up inside gfs_open_com_syntax()

---

internal/c/parts/video/image/stb/stb_image.h

This PR updates `stb_image` to v2.29. This updated version has performance optimizations that can potentially improve the image loading performance of QB64-PE.

Update stb_image to v2.29

---

internal/c/libqb/src/filesystem.cpp

This PR fixes `FILES` to work for cases where `fileSpec$` does not contain a directory.
For example, the following will now correctly assume the current directory.
```vb
FILES "*.bas"
```
This was reported here: https://qb64phoenix.com/forum/showthread.php?tid=2401

Fix FILES to work for cases where fileSpec$ does not contain a directory

---

source/qb64pe.bas

- exclude DECLARE LIBRARY files loaded w/o path from predefined system locations

Fix external dependencies checks

---

source/ide/ide_methods.bas
source/utilities/const_eval.bas
tests/compile_tests/const/expression.bas
tests/compile_tests/const/expression.output

The math evaluator was not running the input through lineformat before
evaluation, resulting in Evaluate_Expression$() giving the wrong result
since the input wasn't tokenized.
I also addressed a bug when doing multiplication with unsigned values.

Fix Math Evaluator

---

.github/workflows/build-process.yml

A few of the actions we use require manual updating to a version that uses node.js v20. None of the changes appear to impact our usage of them.

Remove usage of node.js 16 in workflow

---

source/utilities/const_eval.bas
tests/compile_tests/const/expression.bas
tests/compile_tests/const/expression.output

The regular division symbol always converts its arguments to floating point before dividing, similar to how integer division converts its arguments to integers before dividing.

Fix divide in CONST

---

source/ide/ide_methods.bas
tests/compile_tests/http/http_error.bas

Instead of being disabled by default after certain actions (those which affected the recent files list and so forced a rebuild of the "File" menu), now the current state of the "Export As" item is passed through to the rebuild procedure.
see Discord: https://discord.com/channels/975381912350752819/975389657212805160/1219261946532986880

Fix "Export As" menu state

---

internal/c/libqb.cpp

This PR fixes the issue reported [here](https://qb64phoenix.com/forum/showthread.php?tid=2504&pid=23718#pid23718).
Instead of making custom modifications to FreeGLUT, we will simply add a check within the `GLUT_key_special()` function to monitor special keys only when the QB64 window is in focus.

Avoid monitoring special keys when the window is not in focus

---

internal/c/libqb.cpp
internal/c/libqb/include/datetime.h
internal/c/libqb/src/datetime.cpp
internal/c/libqb/src/glut-main-thread.cpp

Currently the GLUT thread draws the screen too slowly, it is supposed to
default to 60 FPS but you'll always get a bit less than that. This is because
the current logic simply inserts delays for the entire length of a frame, not
taking into account how long it took us to render the last frame. Any time
spent rendering thus results in a slowed down FPS.
The new code uses GetTicks() to measure how much time has passed since
the last render, which then lets us calculate the exact amount of time
until the next frame so we can sleep for that amount. We additionally
then measure how long the sleep lasted vs. what we asked for (since any
sleep we do only has a minimum guarantee, it will occasionally last a bit
longer) and adjust based on that as well. The result is a perfect 60 FPS
as long as …

Fix GLUT thread to redraw at an accurate 60 FPS.

---

internal/c/parts/video/font/font.cpp

This PR addresses an issue initially reported [here](https://qb64phoenix.com/forum/showthread.php?tid=2469&pid=23435#pid23435).
The primary fix ensures accurate generation of mono glyph bitmaps for non-true-color screen modes. Similar adjustments have been made to the calculation of monospace width.
It also introduces a quality-of-life enhancement where the system now automatically detects whether the underlying font is fixed-width. If so, the `monospaceWidth` variable is appropriately updated. This allows `_FONTWIDTH` to accurately report the font width of fixed-width fonts, even in the absence of `"monospace"` usage.

Fix mono-mode font rendering issues

---

Makefile

This pull request addresses an issue where both `-mconsole` and `-mwindows` flags are sent for `DEP_CONSOLE` applications. Typically, this doesn't cause problems with MinGW, as it seems to prioritize `-mconsole`. However, LLVM MinGW gives preference to `-mwindows`, resulting in the complete disabling of the Windows console when `QB64pe.bas` is compiled with LLVM MinGW.
This pull request addresses the final issue remaining from the list of issues I observed when using LLVM MinGW. By resolving this problem, we now have an opportunity to consider moving away from MinGW and adopting LLVM MinGW as the backend for all possible Windows targets in a future PR.

Create Windows GUI applications only when both DEP_CONSOLE_ONLY & DEP_CONSOLE are not defined

---

source/global/version.bas

This version includes the following fixes and changes:
- Fix typos (#467, #483)
- Add support for _MOUSEWHEEL and _MOUSEMOVEMENTx on macOS (#468)
- Fix issues with DATA on macOS (#470)
- Fix "Export As" menu state (#473)
- Fix GLUT thread to redraw at an accurate 60 FPS (#474)
- Add support for _CLIPBOARDIMAGE on macOS & Linux and other clipboard fixes (#475)
- Avoid monitoring special keys (on Windows) when the window is not in focus (#476)
- Open GUI file dialog in the IDE when Ctrl+S is pressed (#477)
- Add support for _NEGATE, _ANDALSO & _ORELSE Boolean operators (#478, #484)
- Fix mono-mode font rendering and quality issues (#480)
- Fix font width calculation when loading monospaced fonts (#487)
- Create Windows GUI applications only when both DEP_CONSOLE_ONLY & DEP_CONSOLE are not …

Bump version to 3.13.0

---

source/ide/ide_methods.bas

Very simple change here, to basically take:
a$ = b$ + c$ + d$ + e$ + f$
And make it:
a$ = b$ + (c$ + d$ + e$) + f$
....
This speeds up the IDE due to (c$ + d$ + e$) being small strings, while a$ and f$ are larger strings...  It's more efficient to move and add those small strings first, than it is to add them to the large strings, making them larger, at each step.

Optimize string addition somewhat to reduce IDE lag

---

internal/c/libqb.cpp
internal/c/parts/core/freeglut/freeglut_window.c
source/ide/ide_methods.bas

The FocusIn/FocusOut X11 events are more reflective of active foreground window that Enter/Leave, which only relates to mouse movement. In particular, FocusOut fires when Alt-Tabbing away so the alt key is correctly released.
Also re-enable IDE defocus processing on Linux so the Alt key no longer keeps the menus selected when Alt-Tabbing. This effectively reverts https://github.com/QB64Team/qb64/pull/1 which as far as I can tell was solely because one person didn't like the defocus behaviour.

Reliably enable window defocus on Linux

---

internal/c/libqb/src/environ.cpp
tests/compile_tests/environ/set_environ.bas
tests/compile_tests/environ/set_environ.output

Fixes #386 which turned out to be an issue with assigning environment variables with values containing spaces.

Allow setting environment variables with space in values

---

source/qb64pe.bas
tests/format_tests/lbound_ubound/layout.out
tests/format_tests/lbound_ubound/lbound_ubound.bas
tests/format_tests/lbound_ubound/lbound_ubound.flagmap
tests/format_tests/lbound_ubound/noformat.out

This commit reverts 38e0ec37 9f81ba1e and 55c36576 which attempted to fix the capitalisation of array names used with L/UBOUND, and introduced the code-eating bug. It is replaced with an alternative solution to the capitalisation issue.
Closes #244

Avoid eating 0-argument functions used after L/UBOUND

---

setup_mingw.cmd

Updates LLVM-MinGW for Windows on ARM to 20240619.

Update to LLVM-MinGW 20240619 with LLVM 18.1.8 for WoA

---

internal/c/libqb/src/filesystem.cpp

This PR addresses a bug in the sub_kill() function, which would previously terminate and fail to process the remaining files if the user opted to continue after an error condition.

Fix sub_kill() bug

---

source/ide/config/cfg_methods.bas
source/ide/ide_global.bas
source/ide/ide_methods.bas
source/ide/wiki/wiki_methods.bas
source/qb64pe.bas
source/subs_functions/subs_functions.bas
source/utilities/strings.bas

- mainly this PR does focus on legacy dialog refactoring and enhancements, starting with the **Option** dialogs, more will follow over time
- fixed some ommisions from my last config related PR
- some minor other things

More ide refactoring

---

source/global/version.bas
source/utilities/type.bas
tests/compile_tests/types/nested_udt.bas
tests/compile_tests/types/nested_udt.output

Fixes an error in the initialisation of variable-length strings in UDTs. Fixes #524 
Also bumps the version to 3.14.0, on the assumption that this is the last feature to go in before release.

Udt string offsets & bump to version 3.14.0

---

internal/c/parts/gui/tinyfiledialogs.c

The syntax used to supply file extension filters to kdialog (KDE implementation for _Open/SaveFileDialog$) was entirely wrong. This now matches what is described in the kdialog manual. Note that my installed version of kdialog have a bug whereby filters without a filter description are ignored, so that functionality has not been tested.

Fix calls to kdialog so filters work

---

internal/c/parts/audio/audio.cpp
internal/c/parts/audio/framework.h
source/global/version.bas

Fixes the issue reported here: https://qb64phoenix.com/forum/showthread.php?tid=2740&pid=27764#pid27764

Use std::hash to generate a proper unique key in _SNDOPEN

---

internal/c/parts/audio/audio.cpp
internal/c/parts/audio/extras/foo_midi/InstrumentBankManager.cpp
internal/c/parts/audio/extras/foo_midi/InstrumentBankManager.h
internal/c/parts/audio/extras/foo_midi/VSTiPlayer.cpp
internal/c/parts/audio/extras/midi_ma_vtable.cpp

The modification enables users to revert to the built-in soundbank by passing an empty string to _MIDISOUNDBANK. Before this change, it was not possible to switch back to the default soundbank once an external one had been used with _MIDISOUNDBANK.

Allow _MIDISOUNDBANK to use the default soundbank

---

source/ide/ide_methods.bas

The "Export As ..." feature now checks for an active selection first. Only if no selection was made, then the entire loaded source file will be exported as usual.

Export enhancement

---

internal/c/qbx.cpp

By default, QB64-PE compiled with MinGW supports command line wildcard expansion. However, this does not seem to be the case when using llvm-mingw. This PR enables globbing by default for Windows regardless of the MinGW toolchain.

Enable globbing by default when using llvm-mingw

---

setup_mingw.cmd
source/qb64pe.bas
source/utilities/s-buffer/readme.txt
source/utilities/s-buffer/simplebuffer.bi
source/utilities/s-buffer/simplebuffer.bm
tests/dist_tests.sh

The PR makes the LLVM MinGW toolchain the only one used on Windows x86, x86-64, AArch32, and AArch64.

Update setup_mingw.cmd to use LLVM MinGW on all versions of Windows

---

internal/c/libqb/src/filesystem.cpp

This PR addresses a bug where KILL, FILES, and _FILES$ unintentionally shared a static `DIR` pointer when performing file searches. As a result, calling any of these functions would reset the search state of _FILES$, leading to unexpected behavior.
Each of these functions (KILL, FILES, and _FILES$) now maintains its own separate directory search state, preventing interference between them.
This issue was reported [here](https://qb64phoenix.com/forum/showthread.php?tid=3112).

Fix shared directory state between KILL, FILES, and _FILES$

---

internal/c/parts/audio/audio.cpp

This PR removes the voice range check in `func_play()`. If the voice is out of range, it now simply defaults to zero, aligning the behavior with QB45 standards.
This issue was identified during a wiki update.

Do not throw an error if voice is out of range in func_play()

---

source/ide/ide_export.bas

This PR just fixes an escaping issue unveiled by the code example provided on the Wiki page https://qb64phoenix.com/qb64wiki/index.php/WAVE , some of the MML music in the DATA lines happend to build the `<b>` combo, which the wiki interpreted as the HTML tag for **bold** text.
Note that this issue only happend because the DATA content is not quoted in that example, one more reason to always use quotes, if the DATA element is not of pure numeric nature.
HTML export already used the proper escaping, the RTF format and Forum Codeboxes don't have the problem.

Fix export as Wiki example

---

README.md
docs/build-system.md
docs/testing.md

This PR is simple: it runs all markdown documents in the repository through a markdown linter and formatter, resolving numerous markdown violations. It replaces HTML anchor tags with markdown internal links and corrects a few typos. The rendered content remains unchanged.

Lint and format markdown

---

internal/c/libqb.cpp

- make the function non-blocking as discussed here https://qb64phoenix.com/forum/showthread.php?tid=3388

Fix _CONSOLEINPUT function

---

internal/c/parts/core/freeglut/freeglut_main.c
setup_mingw.cmd

This PR resolves `_MOUSEMOVEMENTX` and `_MOUSEMOVEMENTY` returning `0` on Windows on ARM with C++ optimizations enabled.

Fix mouse _MOUSEMOVEMENTX/Y issue on Windows on ARM with C++ optimizations

---

internal/c/libqb.cpp
internal/c/libqb/include/filesystem.h
internal/c/libqb/include/mac-mouse-support.h
internal/c/libqb/src/filesystem.cpp
internal/c/libqb/src/glut-message.cpp
internal/c/libqb/src/graphics.cpp
internal/c/libqb/src/mac-mouse-support.cpp

This PR fixes a bug on macOS where mouse events are suppressed for 0.25 seconds when `_MOUSEMOVE` is used. The issue is resolved by calling `CGAssociateMouseAndMouseCursorPosition()`. Note that the event suppression bypass only happens when the mouse is hidden.
Additionally, as discussed on Discord, this PR prevents `_FULLPATH$` from throwing an error when an empty string is passed.

Disables mouse event suppression on macOS when the mouse is hidden and moved

---

source/qb64pe.bas

This fixes an issue on Mac OS where the program compiles successfully but doesn't run unless you toggle the logging output to be displayed.

Fix running executables on Mac OS

---

internal/c/parts/video/image/build.mk
internal/c/parts/video/image/image.cpp
internal/c/parts/video/image/nanosvg/nanosvg.h
internal/c/parts/video/image/pixelscalers/hqx.cpp
internal/c/parts/video/image/pixelscalers/mmpx.cpp
internal/c/parts/video/image/pixelscalers/pixelscalers.h
internal/c/parts/video/image/pixelscalers/sxbr.cpp
internal/c/parts/video/image/sg_curico/sg_curico.cpp
internal/c/parts/video/image/sg_pcx/sg_pcx.cpp

This PR does the following:
- Adds 3x and 4x XBR family pixel scalers.
- Adds support for ImageMagick-generated 32bpp PCX files (see @SteveMcNeill's post [here](https://qb64phoenix.com/forum/showthread.php?tid=3470&pid=32118#pid32118)).
- Cleans up and refactors bits of `image.cpp`, `sg_pcx.cpp`, `sg_curico.cpp`, `mmpx.cpp`, and `hqx.cpp` and suppresses some C++ compiler warnings.

Image library enhancements

---

internal/c/parts/gui/tinyfiledialogs.c

This PR updates `tinyfd_beep()` to play a 900 Hz tone for 500 ms, making the `BEEP` sound closer to its behavior before version 4.x.
Note that on Windows and most platforms, the beep is generated as a sine wave rather than a square or triangle wave, resulting in a softer sound.

Fix BEEP behavior

---

Makefile
source/qb64pe.bas
tests/compile_tests/dollar$sign$test/dollar$sign.bas
tests/compile_tests/dollar$sign$test/dollar$sign.output
tests/compile_tests/parens()/parens().bas
tests/compile_tests/parens()/parens().output

There were several problems identified with the existing escaping for calling `make` - parenthesis at the end would get lost, dollar signs got expanded incorrectly, etc.. This change redoes the escaping and applies it correctly depending on the platform for all three levels of escaping:
1. Makefile command and Shell invocation to run make:
a. Mac OS and Linux use single quotes. Existing single quotes in the name are turned into `'\''` to escape them.
b. Windows gets double quotes and no extra escaping.
3. make invocation:
a. Quotes are escaped with `\"`, Dollar signs with `$$`

Fix Makefile escaping

---

internal/c/libqb.cpp
internal/c/libqb/include/mac-mouse-support.h
internal/c/libqb/src/glut-main-thread.cpp
internal/c/libqb/src/glut-message.cpp
internal/c/libqb/src/mac-mouse-support.cpp
source/qb64pe.bas

This partially reverses the approach taken in #602. Using `CGAssociateMouseAndMouseCursorPosition()` was a mistake - it fixed `_MOUSEMOVEMENTX` and `_MOUSEMOVEMENTY` for FPS-style camera movement but broke `_MOUSEX` and `_MOUSEY` by preventing GLUT from triggering the `glutMotionFunc` callback while the mouse pointer was hidden.
To address this, we now use `CGEventSourceSetLocalEventsSuppressionInterval()` to work around macOS’s 0.25-second event suppression. However, this means `_MOUSEMOVEMENTX` and `_MOUSEMOVEMENTY` remain broken because macOS generates artificial movement events when `glutWarpPointer` is used.
For now, this is an acceptable trade-off. A proper long-term fix depends on implementing #608.
Many thanks to `NakedApe` from the QB64-PE forum for pointing out the issue. See …

Fix _MOUSEX and _MOUSEY when the mouse pointer is hidden on macOS

---

Makefile
internal/c/parts/network/http/build.mk
setup_mingw.cmd
source/ide/config/cfg_global.bas
source/ide/config/cfg_methods.bas
source/ide/ide_methods.bas
source/qb64pe.bas
source/utilities/build.bas

This change adds support for using a system-installed compiler on Windows, such as a pre-existing MinGW toolchain (from MSYS2, Winget etc.). This can be helpful in situations where the user either cannot or prefers not to use the compiler bundled with QB64-PE.
A clear warning is displayed when this option is enabled to ensure users understand the implications. This feature is available exclusively on Windows.

Support Using System MinGW on Windows

---

source/ide/ide_methods.bas

The IDE would crash when a large source file was loaded and the syntax highlighter had to build the list of sub/functions on its own, due to errors in the loaded file preventing compilation from going through.

Fix IDE error when loading large source file

---

source/ide/ide_methods.bas
source/ide/wiki/wiki_global.bas

- now excluding mostly static _GL command pages, i.e. 337 files less to fetch, approx. 2-3 minutes less
- add a missing UTF-8 replacement (€)
- document help flags behavior

Improve "Update All Pages"
